server:
  port: 8080

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8761/eureka

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud-upms?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
    username: root
    password: 123456
