server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: upms-
        uri: lb://UPMS-SERVER
        predicates:
        - Path=/upms/**
        filters:
        - StripPrefix=1
  datasource:
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka