server:
  port: 9000

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

# gateway
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: upms-server
        uri: lb://UPMS-SERVER
        predicates:
        - Path=/upms/**
        filters:
        - StripPrefix=1

      - id: daemon-server
        uri: lb://DAEMON-SERVER
        predicates:
        - Path=/daemon/**
        filters:
        - StripPrefix=1

      - id: auth-server
        uri: lb://AUTH-SERVER
        predicates:
        - Path=/auth/**
        filters:
        - StripPrefix=1
        - SwaggerHeaderFilter

